# generated by datamodel-codegen:
#   timestamp: 2023-10-04T15:20:02+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class PublicKey(BaseModel):
    content: str = Field(
        ...,
        description="Specifies the content of the public key inline within the document",
    )


class AlpineV001Schema(BaseModel):
    public_key: PublicKey = Field(
        ...,
        alias="publicKey",
        description="The public key that can verify the package signature",
    )


class AlpinePackageSchema(RootModel[AlpineV001Schema]):
    root: AlpineV001Schema = Field(
        ...,
        description="Schema for Alpine package objects",
        title="Alpine Package Schema",
    )
