# generated by datamodel-codegen:
#   timestamp: 2023-10-04T15:20:04+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, RootModel


class PublicKey(BaseModel):
    content: str = Field(
        ...,
        description=(
            "Specifies the content of the X509 certificate containing the public key used to verify"
            " the signature"
        ),
    )


class Signature(BaseModel):
    content: str = Field(
        ...,
        description="Specifies the PKCS7 signature embedded within the JAR file ",
    )
    public_key: PublicKey = Field(
        ...,
        alias="publicKey",
        description=(
            "The X509 certificate containing the public key JAR which verifies the signature of"
            " the JAR"
        ),
    )


class JarV001Schema(BaseModel):
    signature: Optional[Signature] = Field(
        None,
        description="Information about the included signature in the JAR file",
    )


class JarSchema(RootModel[JarV001Schema]):
    root: JarV001Schema = Field(..., description="Schema for JAR objects", title="JAR Schema")
