# generated by datamodel-codegen:
#   timestamp: 2023-10-04T15:20:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class Tsr(BaseModel):
    content: str = Field(
        ...,
        description="Specifies the tsr file content inline within the document",
    )


class Rfc3161V001Schema(BaseModel):
    tsr: Tsr = Field(..., description="Information about the tsr file associated with the entry")


class TimestampSchema(RootModel[Rfc3161V001Schema]):
    root: Rfc3161V001Schema = Field(
        ...,
        description="Schema for RFC 3161 timestamp objects",
        title="Timestamp Schema",
    )
