# generated by datamodel-codegen:
#   timestamp: 2023-10-04T15:20:04+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class PublicKey(BaseModel):
    content: str = Field(
        ...,
        description="Specifies the content of the public key inline within the document",
    )


class RpmV001Schema(BaseModel):
    public_key: PublicKey = Field(
        ...,
        alias="publicKey",
        description="The PGP public key that can verify the RPM signature",
    )


class RpmSchema(RootModel[RpmV001Schema]):
    root: RpmV001Schema = Field(..., description="Schema for RPM objects", title="RPM Schema")
